'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LoginRegister

    '''<summary>
    '''lblLoginMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLoginMail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbxLoginMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxLoginMail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvLoginMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvLoginMail As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblLoginPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLoginPass As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbxLoginPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxLoginPass As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvLoginPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvLoginPass As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblLoginMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLoginMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLogin As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblRegisterMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegisterMail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbxRegisterMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxRegisterMail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvRegisterMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvRegisterMail As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblExistingMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExistingMail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRegisterPass1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegisterPass1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbxRegisterPass1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxRegisterPass1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvRegisterPass1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvRegisterPass1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblRegisterPass2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegisterPass2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbxRegisterPass2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxRegisterPass2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvRegisterPass2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvRegisterPass2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cpvRegisterPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpvRegisterPass As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''btnRegister control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRegister As Global.System.Web.UI.WebControls.Button
End Class
