'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Product1

    '''<summary>
    '''tbxQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxQuantity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvQuantity As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cvQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvQuantity As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''lbtAddCart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtAddCart As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtBuyNow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtBuyNow As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lvPostedcomments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvPostedcomments As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''tbxReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbxReview As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRate As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''fupReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fupReview As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btnPost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPost As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As webapp_assignment.Main
        Get
            Return CType(MyBase.Master, webapp_assignment.Main)
        End Get
    End Property
End Class
